import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  X, 
  Search, 
  BookOpen, 
  Info, 
  HelpCircle, 
  Wallet, 
  Receipt, 
  TrendingUp, 
  LineChart, 
  FileText 
} from "lucide-react";

interface GuideGlossaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  currency: string;
}

interface GlossaryItem {
  term: string;
  category: "general" | "income" | "expenses" | "portfolio" | "projection";
  definition: string;
  formula?: string;
  tip?: string;
}

export default function GuideGlossaryModal({ isOpen, onClose, currency }: GuideGlossaryModalProps) {
  const [activeTab, setActiveTab] = useState<"glossary" | "guide">("glossary");
  const [glossaryCategory, setGlossaryCategory] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState<string>("");

  const glossaryItems: GlossaryItem[] = [
    {
      term: "In-Hand Salary",
      category: "income",
      definition: "Your net monthly take-home pay received after standard income tax deductions at source.",
      formula: `Net Salary = Gross Salary - Tax Deductions`,
      tip: "Use this to represent your stable primary cash inflow before any investment or lifestyle planning is computed."
    },
    {
      term: "Additional Streams",
      category: "income",
      definition: "Secondary source of incomes like freelancing, dividends, rentals, passive interest, or online businesses.",
      tip: "Categorizing passive and active income helps assess your overall financial security separate from your primary job."
    },
    {
      term: "Savings Target",
      category: "general",
      definition: "The targeted amount of money you intend to set aside each month for compounding and emergency funds.",
      tip: "Adjust this target using the slider on the main hub header to benchmark your actual monthly leftover savings."
    },
    {
      term: "Savings Rate",
      category: "general",
      definition: "The percentage of your total income that is saved after all monthly expenditures are paid.",
      formula: `Savings Rate (%) = (Net Savings / Total Income) * 100`,
      tip: "A savings rate of 30-50% is generally considered excellent for rapid long-term wealth compounding."
    },
    {
      term: "Category Budgets",
      category: "expenses",
      definition: "Configurable maximum monthly spending limits assigned to different standard lifestyle expenditure categories.",
      tip: "When your logs in any category exceed its designated budget, a high-contrast overspend alert will automatically trigger on the dashboard."
    },
    {
      term: "SIP (Systematic Investment Plan)",
      category: "portfolio",
      definition: "A method of investing fixed amounts regularly (usually monthly) into mutual funds, ETFs, or equities.",
      formula: `Future Value = P * [((1 + r)^n - 1) / r] * (1 + r)`,
      tip: "SIPs benefit from rupee-cost averaging and compound growth, smoothing out market volatility over long horizons."
    },
    {
      term: "Exit Brokerage",
      category: "portfolio",
      definition: "A transaction commission or fee calculated as a percentage of the total final asset valuation upon liquidation or sale.",
      formula: `Exit Fee = Current Asset Value * (Exit Brokerage % / 100)`,
      tip: "Commonly applied to real estate broker commissions (1-2%) or stockbroker sales fees. Modeling this prevents overestimating actual liquid cash reserves."
    },
    {
      term: "Capital Gains Tax",
      category: "portfolio",
      definition: "A taxation levied on the net profit (gain) realized from selling an asset, rather than on the total principal.",
      formula: `Tax Amount = (Current Value - Total Principal) * (Gains Tax % / 100)`,
      tip: "You can apply a specific tax rate override per investment, or inherit the global rate specified in the 'Assumptions' settings."
    },
    {
      term: "Rental Yield",
      category: "portfolio",
      definition: "The annual rental income generated by an asset (such as a Flat or Land) expressed as a percentage of its purchase price.",
      formula: `Rental Yield (%) = (Annual Rent / Purchase Price) * 100`,
      tip: "A rental yield of 2.5% to 4% is typical for residential flats, while commercial properties can go higher."
    },
    {
      term: "Annual Return Rate / CAGR",
      category: "portfolio",
      definition: "The Compound Annual Growth Rate representing the speed at which your asset's value expands organically year-on-year.",
      tip: "Equity typically averages 10-12% long-term, gold 6-8%, and Fixed Deposits (FDs) earn a steady 5-7% with zero risk."
    },
    {
      term: "Inflation Rate",
      category: "projection",
      definition: "The rate at which the general level of prices for goods and services rises, diminishing future purchasing power.",
      tip: "In the Projections tab, toggle 'Adjust for Inflation' to view what your future millions will feel like in today's currency equivalent."
    }
  ];

  // Filtering Glossary Items
  const filteredGlossary = glossaryItems.filter(item => {
    const matchesCategory = glossaryCategory === "all" || item.category === glossaryCategory;
    const matchesSearch = 
      item.term.toLowerCase().includes(searchQuery.toLowerCase()) || 
      item.definition.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (item.formula && item.formula.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop Blur */}
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-slate-900/45 backdrop-blur-md"
          />

          {/* Modal Container */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: "spring", damping: 25, stiffness: 350 }}
            className="relative w-full max-w-3xl h-[85vh] flex flex-col nm-flat bg-slate-50 rounded-3xl border border-white/40 shadow-2xl overflow-hidden z-10"
          >
            {/* Header */}
            <div className="p-6 border-b border-slate-200/50 flex justify-between items-center bg-slate-100/30">
              <div className="flex items-center gap-3">
                <div className="nm-pressed p-2.5 rounded-2xl text-indigo-600">
                  <BookOpen className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold font-display text-slate-800">Knowledge Base</h2>
                  <p className="text-[10px] text-slate-400 font-mono">Guide & Glossary for Neo Finance Planner</p>
                </div>
              </div>
              <button 
                onClick={onClose}
                className="nm-btn p-2 rounded-2xl text-slate-400 hover:text-slate-600 transition-colors"
                aria-label="Close knowledge base modal"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Sub Tabs */}
            <div className="flex px-6 pt-4 gap-2 bg-slate-100/10 border-b border-slate-200/40">
              <button
                onClick={() => setActiveTab("glossary")}
                className={`px-4 py-2 text-xs font-bold rounded-t-2xl transition-all cursor-pointer ${
                  activeTab === "glossary" 
                    ? "nm-pressed text-indigo-600 bg-slate-50 border-t-2 border-indigo-500" 
                    : "text-slate-500 hover:text-slate-700 hover:bg-slate-100/50"
                }`}
              >
                📊 Terminology Glossary
              </button>
              <button
                onClick={() => setActiveTab("guide")}
                className={`px-4 py-2 text-xs font-bold rounded-t-2xl transition-all cursor-pointer ${
                  activeTab === "guide" 
                    ? "nm-pressed text-indigo-600 bg-slate-50 border-t-2 border-indigo-500" 
                    : "text-slate-500 hover:text-slate-700 hover:bg-slate-100/50"
                }`}
              >
                💡 Component User Guide
              </button>
            </div>

            {/* Scrollable Content Area */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              
              {/* GLOSSARY TAB */}
              {activeTab === "glossary" && (
                <div className="space-y-5">
                  
                  {/* Search and Category Filters */}
                  <div className="flex flex-col sm:flex-row gap-3">
                    {/* Search bar */}
                    <div className="relative flex-1">
                      <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                      <input 
                        type="text"
                        placeholder="Search formulas, definitions, terms..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="nm-input w-full pl-10 pr-4 py-2 rounded-2xl text-xs font-medium focus:ring-1 focus:ring-indigo-400 focus:outline-none"
                      />
                    </div>

                    {/* Filter categories */}
                    <div className="flex gap-1 overflow-x-auto pb-1 scrollbar-none">
                      {["all", "income", "expenses", "portfolio", "projection"].map((cat) => (
                        <button
                          key={cat}
                          onClick={() => setGlossaryCategory(cat)}
                          className={`px-3 py-1.5 rounded-xl text-[10px] font-bold uppercase tracking-wider font-mono transition-all cursor-pointer ${
                            glossaryCategory === cat 
                              ? "bg-indigo-100 text-indigo-700 font-extrabold" 
                              : "bg-slate-100 text-slate-500 hover:bg-slate-200/50"
                          }`}
                        >
                          {cat}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Glossary Cards List */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {filteredGlossary.length > 0 ? (
                      filteredGlossary.map((item, index) => (
                        <div 
                          key={item.term} 
                          className="nm-flat p-4 rounded-2xl border border-white/60 hover:border-indigo-100/80 transition-all flex flex-col justify-between"
                        >
                          <div>
                            <div className="flex items-center justify-between gap-2 mb-2">
                              <h4 className="text-sm font-extrabold text-slate-800 font-display">{item.term}</h4>
                              <span className="text-[9px] font-mono font-bold uppercase tracking-widest px-2 py-0.5 rounded-full bg-slate-200/50 text-slate-500">
                                {item.category}
                              </span>
                            </div>
                            <p className="text-xs text-slate-600 leading-relaxed">{item.definition}</p>
                          </div>

                          {/* Specific Formula or Tips */}
                          {(item.formula || item.tip) && (
                            <div className="mt-3.5 pt-3.5 border-t border-slate-200/50 space-y-2">
                              {item.formula && (
                                <div className="p-2 rounded-xl bg-slate-100/50 font-mono text-[10px] text-indigo-700 font-bold border border-indigo-50/20">
                                  {item.formula}
                                </div>
                              )}
                              {item.tip && (
                                <div className="text-[10px] text-amber-600 flex items-start gap-1">
                                  <Info className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                                  <span className="font-medium italic leading-relaxed">{item.tip}</span>
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      ))
                    ) : (
                      <div className="col-span-1 md:col-span-2 text-center py-10 text-slate-400 font-mono text-xs">
                        No glossary terms found matching your query.
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* USER GUIDE TAB */}
              {activeTab === "guide" && (
                <div className="space-y-6">
                  
                  {/* Guide Header Intro */}
                  <div className="p-4 rounded-2xl bg-indigo-50/40 border border-indigo-100/30">
                    <p className="text-xs text-indigo-700 font-medium leading-relaxed">
                      💡 Welcome to the <strong>Neo Finance Planner</strong>! This application leverages a real-time, zero-round-trip financial math engine. Changes made anywhere (to income, taxes, or compounding rates) update your entire portfolio valuation and future projections instantly.
                    </p>
                  </div>

                  {/* Component breakdowns */}
                  <div className="space-y-5">
                    
                    {/* 1. Hub Screen */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <HelpCircle className="w-5 h-5 text-indigo-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">1. Financial Hub (Main Dashboard)</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Your central control board. It displays a macro-view of your <strong>Total Income</strong>, <strong>Monthly Expenditures</strong>, <strong>Net Leftover Cash Savings</strong>, and <strong>Total Portfolio Value</strong>.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Use the <strong className="text-slate-600">Target Savings</strong> slider at the top to set a standard baseline.</li>
                          <li>Review the <strong className="text-slate-600">Budget Warning Alerts</strong> panel to see where you are approaching or exceeding your category spending limits.</li>
                        </ul>
                      </div>
                    </div>

                    {/* 2. Income Manager */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <Wallet className="w-5 h-5 text-emerald-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">2. Income Stream Allocation</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Fine-tune where your capital originates. Configure your primary stable salary and additional monthly streams.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Drag the <strong className="text-slate-600">Salary Slider</strong> or input an exact value directly.</li>
                          <li>Add diverse streams (Freelancing, Rental, Dividends) with custom labels to construct a robust monthly cash inflow.</li>
                        </ul>
                      </div>
                    </div>

                    {/* 3. Expense Tracker */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <Receipt className="w-5 h-5 text-amber-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">3. Expenses & Category Budgets</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Log where your money flows. Establish monthly budgets for essential and leisure categories.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Review the elegant <strong className="text-slate-600">Interactive Breakdown Pie Chart</strong> to see your spending ratios.</li>
                          <li>Click <strong className="text-slate-600">Edit Budgets</strong> directly in the category rows to change target caps dynamically.</li>
                        </ul>
                      </div>
                    </div>

                    {/* 4. Asset Portfolio Allocation */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <TrendingUp className="w-5 h-5 text-purple-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">4. Portfolio Compounding Engine</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Allocate your wealth into distinct asset classes. We support mutual funds, FDs, physical land, gold, and real estate.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Assign specific <strong className="text-slate-600">Capital Gains Tax</strong> overrides to model your tax liability when selling.</li>
                          <li>Specify <strong className="text-slate-600">Exit Brokerage %</strong> (such as real estate transaction fees) to compute actual net liquidation values.</li>
                        </ul>
                      </div>
                    </div>

                    {/* 5. Wealth Projections */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <LineChart className="w-5 h-5 text-indigo-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">5. Multi-Decade Wealth Compounder</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Simulate compounding over 10, 20, 30, or 40 years based on active growth and continuous monthly additions.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Hover over the bar graphs to see expected savings vs compounded interest yields.</li>
                          <li>Adjust the timeline and assumptions to see the powerful impact of early retirement planning.</li>
                        </ul>
                      </div>
                    </div>

                    {/* 6. Financial Footprint Report */}
                    <div className="flex gap-4 items-start">
                      <div className="nm-flat p-2.5 rounded-2xl text-slate-600 flex-shrink-0">
                        <FileText className="w-5 h-5 text-rose-500" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="text-sm font-extrabold text-slate-800 font-display">6. Statement Exporting</h4>
                        <p className="text-xs text-slate-500 leading-relaxed">
                          Compile your entire plan into an elegant, flat statement of financial health.
                        </p>
                        <ul className="list-disc pl-4 text-[11px] text-slate-400 space-y-1">
                          <li>Review active cash flows, portfolio allocations, and net liquidation estimates.</li>
                          <li>Use the <strong className="text-slate-600">Print Statement / Save PDF</strong> button to generate standard off-line documents.</li>
                        </ul>
                      </div>
                    </div>

                  </div>
                </div>
              )}

            </div>

            {/* Footer / Close Button */}
            <div className="p-5 border-t border-slate-200/50 flex justify-end bg-slate-100/30">
              <button
                onClick={onClose}
                className="nm-btn px-6 py-2.5 rounded-2xl text-xs font-bold text-indigo-600 hover:text-indigo-800 transition-all cursor-pointer"
              >
                Close Knowledge Base
              </button>
            </div>

          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
